services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.4.2-noble
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - MARIADB_ROOT_PASSWORD=II039WoaiZA
      - MARIADB_USER=recomotor
      - MARIADB_PASSWORD=recomotor
      - MARIADB_DATABASE=recomotordb
    ports:
      - "3306:3306"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - mariadb_data:/var/lib/mysql
      - /var/docker/mariadb/conf:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=root --password=II039WoaiZA --host=localhost ping"]
      start_period: 60s
      start_interval: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - recomotor-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=recomotor
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=root
      - MARIADB_PASSWORD=II039WoaiZA
      - MARIADB_DATABASE=recomotordb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - recomotor-network

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
      args:
        - VITE_API_EXPRESS=http://localhost/api
    container_name: frontend_build_container
    volumes:
      - react_build:/app/dist
    networks:
      - recomotor-network

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - react_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-build
      - backend
    networks:
      - recomotor-network

volumes:
  mariadb_data:
    driver: local
  react_build:
    driver: local

networks:
  recomotor-network:
    driver: bridge